// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Identity and Access Management system
//
//  Identity and Access Management system swagger api document
//  Terms Of Service:
//    iam
//  Schemes:
//    http
//    https
//  Host: iam.api.marmotedu.com
//  BasePath: /v1
//  Version: 0.1.0
//  Contact: colin<colin404@foxmail.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
