// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Identity and Access Management system swagger api document",
    "title": "Identity and Access Management system",
    "termsOfService": "iam",
    "contact": {
      "name": "colin",
      "email": "colin404@foxmail.com"
    },
    "version": "0.1.0"
  },
  "host": "iam.api.marmotedu.com",
  "basePath": "/v1",
  "paths": {
    "/secrets": {
      "get": {
        "tags": [
          "todos"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "default": 0,
            "name": "expires",
            "in": "header"
          },
          {
            "type": "string",
            "name": "description",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": "list the todo operations",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/item"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "item": {
      "type": "object",
      "required": [
        "description"
      ],
      "properties": {
        "completed": {
          "type": "boolean"
        },
        "description": {
          "type": "string",
          "minLength": 1
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Identity and Access Management system swagger api document",
    "title": "Identity and Access Management system",
    "termsOfService": "iam",
    "contact": {
      "name": "colin",
      "email": "colin404@foxmail.com"
    },
    "version": "0.1.0"
  },
  "host": "iam.api.marmotedu.com",
  "basePath": "/v1",
  "paths": {
    "/secrets": {
      "get": {
        "tags": [
          "todos"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "default": 0,
            "name": "expires",
            "in": "header"
          },
          {
            "type": "string",
            "name": "description",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": "list the todo operations",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/item"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "item": {
      "type": "object",
      "required": [
        "description"
      ],
      "properties": {
        "completed": {
          "type": "boolean"
        },
        "description": {
          "type": "string",
          "minLength": 1
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        }
      }
    }
  }
}`))
}
